# Development Environment (WSL2)
# Serves site locally at http://localhost
# nginx-cv.dev.conf
server {
    # I think we need to have some thing making sure only cloudflare can connect \
     # in the Tunnel? Like a whitelist? 
    listen 80;
     # http 
    server_name localhost;
    root /home/gustav/cv;
     # This is the dir that nginx looks for.
     # when someone asks for gustavbjorelius.dev/index.php they look for it at \
     # root + /index.php
    index index.php;
    location ~ \.php$ {
     # ~ == regex
     # \.php$ == 'ending in php'
     # this is a pattern match, meaning, any request ending in .php gets handled by \
     # this block 
        include snippets/fastcgi-php.conf;
         # since nginx and php are separate programs, there needs to be a program \
         # that bridges them. FastCGI is that. When nginx hands off a .php file to \
         # PHP-FPM, it must include metadata such as full path to the script, method\
         # such as POST/GET, what's the query string? 
         # this comes with, we can include it, no need to write this ourselves 
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
         # what and why
    }
}
