# Production Environment on Banhof VPS
# Cloudflare Tunnel forwards trafic to this port 80
server {
    listen 80;
    server_name gustavbjorelius.dev;
    root /var/www/cv;
    index index.php;
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
         # after installation of php
         # check if this is true; run ls /run/php; see if its php-fpm OR phpx.x-fpm
    }
}
