# Development Environment (WSL2)
# Serves site locally at http://localhost
# nginx-cv.dev.conf
server {
    # I think we need to have some thing making sure only cloudflare can connect \
     # in the Tunnel? Like a whitelist? 
    listen 80;
     # http 
    server_name localhost;
    root /home/gustav/cv;
     #  
    index index.php;
    location ~ \.php$ {
     # what is this and why? I need to understand my code. 
        include snippets/fastcgi-php.conf;
         # what and why
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
         # what and why
    }
}
